### ISSUE TITLE
brewパッケージとcaskパッケージが入らない…

### ISSUE THREAD

**Issue by answer-d** [answer-d/mac_os_setup_playbook#30]
```console
$ ansible-playbook setup.yml --diff -v
Using /Users/answer_d/mac_os_setup_playbook/ansible.cfg as config file
BECOME password: 

PLAY [setup mac os] **************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

...

TASK [homebrew : brewパッケージのインストール] ***********************************************************************************************************************************************************************************************************

TASK [homebrew : caskパッケージのインストール] ***********************************************************************************************************************************************************************************************************
ok: [localhost] => (item={'name': 'visual-studio-code'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "visual-studio-code"}, "msg": "Cask already installed: visual-studio-code"}
```

**Comment by answer-d** [comment]
metaで書いてる `homebrew` ロールを呼ぶ処理が影響してるっぽい

```yaml
---
dependencies:
  - role: homebrew
     vars:
       homebrew_packages:
         - {name: fish}
       homebrew_cask_packages: []
```

これをこんな感じに書き換えたら変数読み込まれた

```yaml
---
dependencies:
  - role: homebrew
    homebrew_packages:
      - {name: fish}
    homebrew_cask_packages: []
```
